export const TASK_TYPES = {
    SET_TASK_LIST: 'SET_TASK_LIST',
    SET_TASK: 'SET_TASK',
    SET_PHONE: 'SET_PHONE',
    SET_FIRST_NAME: 'SET_FIRST_NAME',
    SET_LAST_NAME: 'SET_LAST_NAME',
    SET_FIRST_NAME: 'SET_FIRST_NAME',
    CLEAR_SET_TASK: 'CLEAR_SET_TASK',
};